---
- name: Assert facts
  assert:
    that:
      - redis_network_range is defined

- name: Find Redis IP
  set_fact:
    redis_bind_ip: '{{ ansible_all_ipv4_addresses | ipaddr(redis_network_range) | max }}'
