---
- include_tasks: ./facts.yml

- name: Pull redis exporter image
  docker_image:
    source: pull
    name: oliver006/redis_exporter
    force: true

- name: Start container
  docker_container:
    comparisons:
      '*': strict
    image: oliver006/redis_exporter
    name: redis_exporter
    restart_policy: unless-stopped
    memory: '{{ ansible_memory_mb.real.total * 0.1 }}m'
    cpu_shares: '{{ (1024 * 0.1) | int }}'
    network_mode: host
    command: '-web.listen-address={{ redis_bind_ip }}:9121'
