---
- include_tasks: ./facts.yml

- name: Create Redis dir
  file:
    state: directory
    path: /opt/redis/data
    recurse: true
    mode: 0777

- set_fact:
    is_replica: '{{ inventory_hostname != redis_primary }}'

- when: is_replica
  block:
    - name: Check that the master host exists
      assert:
        that:
          - redis_primary in hostvars

    - name: Gather Redis master facts
      setup:
      delegate_to: '{{ redis_primary }}'
      delegate_facts: true

    - name: Set Redis master IP
      set_fact:
        redis_primary_ip: "{{ hostvars[redis_primary].ansible_all_ipv4_addresses | ipaddr(redis_network_range) | max }}"

- name: Template Redis config
  register: template_config
  template:
    src: redis.conf
    dest: /opt/redis/redis.conf

- name: Pull Redis container
  docker_image:
    source: pull
    name: redis:latest

- name: Start Redis
  docker_container: '{{ redis_docker_container_defaults | combine(redis_docker_container) }}'

- include_tasks: ./wait_for_port.yml
  vars:
    port: '{{ redis_port }}'

- include_tasks: ./check_master_status.yml
