---
dependency:
  name: galaxy
driver:
  name: ec2
platforms:
  - &common
    name: primary-1
    vpc_subnet_id: subnet-1efffb7b
    image: ami-0c48db26521ca9f07
    instance_type: m5.xlarge
    groups: [redis-cluster-1, sentinel-1]
  - <<: *common
    name: replica-1
    groups: [redis-cluster-1]
  - <<: *common
    name: replica-2
    groups: [redis-cluster-1, sentinel-1]
  - <<: *common
    name: sentinel
    groups: [sentinel-1]
  - <<: *common
    name: standalone
    groups: [all]
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      host_key_checking: false
      pipelining: true
  inventory:
    group_vars:
      all:
        redis_network_range: '172.31.0.0/20'
        molecule_no_log: false
      redis-cluster-1:
        redis_primary: primary-1
      sentinel-1:
        redis_primary: primary-1
verifier:
  name: testinfra
  directory: ../../tests
  options:
    reruns: '3'
    reruns-delay: '2'
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - converge
    - side_effect
    - verify
    - cleanup
    - destroy
